### ISSUE TITLE
Segfault on restoring session…

### ISSUE THREAD

**Issue by katyo** [gat3way/hashkill#29]
```
(gdb) run -p keyring -f ../../keyrings/login.keyring -r markov -a 5:8:rockyou:1000 -s 29063-gpu
Starting program: ./src/hashkill -p keyring -f ../../keyrings/login.keyring -r markov -a 5:8:rockyou:1000 -s 29063-gpu
[hashkill] Version 0.3.1
[New Thread 0x7ffff6997700 (LWP 19631)]
[hashkill] Scheduler initialized.
[hashkill] Plugin 'keyring' loaded successfully
[hashkill] Rule based attack, using rule:markov
[hashkill] Restoring session from: /home/kayo/.hashkill/sessions/29063-gpu.session

Program received signal SIGSEGV, Segmentation fault.
0x000000000065d730 in json_object_object_get ()
(gdb) backtrace 
#0  0x000000000065d730 in json_object_object_get ()
#1  0x0000000000475fea in session_restore (sessionname=0x7fffffffe538 "29063-gpu") at sessions.c:996
#2  0x0000000000405758 in main (argc=11, argv=0x7fffffffe188) at main.c:461
```

```
$ cat ~/.hashkill/sessions/29063-gpu.session 
{ "rule": { "rulefile": "markov", "currentelem": "309002236", "overall": "153895021500", "overallcount": "153895021500", "currentcount": "309002236" }, "hashlist": [ { "username": "login.keyring", "hash": "01234567890abcdef01234567890abcdef", "salt": "123", "salt2": "                              " } ], "crackedlist": [ ] }
```

**Comment by gat3way** [comment]
Thanks for reporting. This should be now fixed with commit 150a01e58d5364b3bcff3abb054ea2890bff8bee
