### ISSUE TITLE
hashkill crashes when cracking a zip file

### ISSUE THREAD

**Issue by kholia** [gat3way/hashkill#6]
Most likely the problem is in restoring session state. 

Session Data: http://dl.dropbox.com/u/1522424/hashkill.sessions.tar

```

$ gdb --args hashkill -pzip -f ~/cmiyc/cmiyc_2012_challenge_files/zip-easy.zip -N6 -t1 -G2 
gdb: warning: error finding working directory: No such file or directory
GNU gdb (GDB) 7.5
Starting program: /usr/local/bin/hashkill -pzip -f /home/user/cmiyc/cmiyc_2012_challenge_files/zip-easy.zip -N6 -t1 -G2
[hashkill] Version 0.3.0
[[hashkill] Scheduler initialized.
[hashkill] Plugin 'zip' loaded successfully
[hashkill] Found >= 1 password-protected files in archive!
[hashkill] File /home/user/cmiyc/cmiyc_2012_challenge_files/zip-easy.zip loaded successfully
[hashkill] CPU features: SSE2 SSE3
[hashkill] Detected 3 CPUs.
[hashkill] Found GPU device: Advanced Micro Devices, Inc. - Cayman
[hashkill] Temperature threshold set to 90 degrees C
[hashkill] GPU0: AMD Radeon HD 6900 Series  [busy:0%] [temp:60C]
[hashkill] Loading markov statfile (rockyou)
[hashkill] This plugin supports GPU acceleration.
[hashkill] Attack has O(N) complexity
[hashkill] Markov max len: 6 threshold:1000
[hashkill] Progress indicator will be available once Markov calculations are done...
[hashkill] Loading kernel: /usr/local/share/hashkill/kernels/amd_zip_long__Cayman.bin
Progress: 0%   Speed: 38M c/s (avg: 38M c/s)  Cracked: 0 passwords                           
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeee09700 (LWP 22637)]
0x00007ffff696e251 in __strlen_sse2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff696e251 in __strlen_sse2 () from /usr/lib/libc.so.6
#1  0x00007ffff696dec6 in strdup () from /usr/lib/libc.so.6
#2  0x00007ffff6eb12b1 in json_object_new_string () from /usr/lib/libjson.so.0
#3  0x000000000048a8f6 in ?? ()
#4  0x00000000004a8d79 in ?? ()
#5  0x00007ffff6c99e0f in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff69d145d in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by kholia** [comment]
Removing ".hashkill" folder didn't fix the problem. hashkill started working again after a reboot. I am not sure why hashkill was crashing earlier.

**Comment by gat3way** [comment]
Hello kholia,

Do you remember the session id that crashed upon restore?

**Comment by gat3way** [comment]
I just noticed you were using -t1. gpu-platform was not stored in the session file which caused various....strange effects. With the latest commit, it is already stored. Could you please retry with the newest files from the git repo?

**Comment by kholia** [comment]
I haven't been able to reproduce the problem with latest git code (dae016dda9).
